In [1]:
!pip install numpy

In [5]:
import numpy as np

In [7]:
a = np.array([1,2,3,4,5,'a'])

In [8]:
a

array(['1', '2', '3', '4', '5', 'a'], dtype='<U21')

In [9]:
a = np.array([1,2,3,4,5,5.7])

In [10]:
a

array([1. , 2. , 3. , 4. , 5. , 5.7])

In [11]:
a = np.array([1,2,3,4,5,])

In [12]:
a

array([1, 2, 3, 4, 5])

In [14]:
a= np.array(10)
b= np.array([1,2,3])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6],[1,2,3],[4,5,6]]])


In [15]:
print('a dimension:',a.ndim)
print('b dimension:',b.ndim)
print('c dimension:',c.ndim)
print('d dimension:',d.ndim)

a dimension: 0
b dimension: 1
c dimension: 2
d dimension: 3


In [16]:
print(a)
print('shape of a:',a.shape)
print(b)
print('shape of b:',b.shape)
print(c)
print('shape of c:',b.shape)
print(d)
print('shape of d:',d.shape)


10
shape of a: ()
[1 2 3]
shape of b: (3,)
[[1 2 3]
 [4 5 6]]
shape of c: (3,)
[[[1 2 3]
  [4 5 6]
  [1 2 3]
  [4 5 6]]]
shape of d: (1, 4, 3)


In [17]:
print(a.dtype)
print(b.dtype)
print(c.dtype)
print(d.dtype)

int64
int64
int64
int64


In [18]:
print(type(a))
print(type(b))
print(type(c))
print(type(d))


<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [24]:
len(d)


1

In [25]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [27]:
np.eye(8,dtype= int)

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1]])

In [28]:
np.eye(5,dtype= int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [30]:
np.zeros((10,8),dtype ='int')

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [32]:
np.ones((6,6),dtype ='int')

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [35]:
np.full((8,5),7,dtype='int')

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [37]:
x=[25,3,3,4,5,6,7,8,9,50]
np.diag(x)

array([[25,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  3,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  3,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  4,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  5,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  6,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  7,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  8,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  9,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 50]])

In [38]:
x=np.arange(1,17)
print(x)
print(x.shape)
print(x.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
(16,)
1


In [41]:
n=x.reshape((4,4))#2d
print(n)
print(n.shape)
print(n.ndim)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
(4, 4)
2


In [42]:
n1=n.reshape((4,2,2))
print(n1)
print(n1.shape)
print(n1.ndim)


[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]
(4, 2, 2)
3


In [45]:
v=n.ravel()
print(v.shape)
print(v)
print(v.ndim)


(16,)
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
1


In [49]:
print(x)
x.reshape((2,4,2))
x.flatten


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


<function ndarray.flatten>

In [50]:
a=np.arange(2,17,2)
a

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [55]:
print(a[7])

16


In [56]:
a[2:6]

array([ 6,  8, 10, 12])

In [57]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
print(a[1,1])

5


In [59]:
print(a[2,0])

7


In [69]:
b=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
b.shape
b


array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])

In [73]:
print(b[0][1][1])

5


In [78]:
x1=np.arange(10)
x1
array =([0,1,2,3,4,5,6,7,8,9])
x2=x1
print(x1)
print(x2)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [79]:
x2[0]=10
print(x1)
print(x2)

[10  1  2  3  4  5  6  7  8  9]
[10  1  2  3  4  5  6  7  8  9]


In [80]:
print(id(x1))
print(id(x2))

140413482523248
140413482523248


In [87]:
print(np.shares_memory(x2,x1))
print(id(x1))
print(id(x2))


True
140413482523248
140413482523248


In [89]:
x3=x1.view()
np.shares_memory(x2,x3)

True

In [91]:
x3[0] = 100
print(x1)
print(x3)

[100   1   2   3   4   5   6   7   8   9]
[100   1   2   3   4   5   6   7   8   9]


In [95]:
x4 = np.copy(x1)
x4[-1] = 900
print(x1)
print(x4)

[100   1   2   3   4   5   6   7   8   9]
[100   1   2   3   4   5   6   7   8 900]


In [96]:
print(x1)
print(x4)
np.shares_memory(x1,x4)

[100   1   2   3   4   5   6   7   8   9]
[100   1   2   3   4   5   6   7   8 900]


False

In [104]:
a[a>3]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [111]:
x1==x4
# print(x1)
# print(x4)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False])

In [113]:
print(a.transpose())
print(a)

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [114]:
print(x1)
print(x4)
np.vstack((x1,x4))

[100   1   2   3   4   5   6   7   8   9]
[100   1   2   3   4   5   6   7   8 900]


array([[100,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [100,   1,   2,   3,   4,   5,   6,   7,   8, 900]])

In [116]:
np.hstack((x1,x4))
print(x1)
print(x4)


[100   1   2   3   4   5   6   7   8   9]
[100   1   2   3   4   5   6   7   8 900]


In [119]:
print(x1)
print(x4)
np.insert(x1,,x4)

[100   1   2   3   4   5   6   7   8   9]
[100   1   2   3   4   5   6   7   8 900]


array([100,   1,   2,   3, 100,   1,   2,   3,   4,   5,   6,   7,   8,
       900,   4,   5,   6,   7,   8,   9])

In [121]:
print(x1)
print(x4)
np.insert(x1,[1,2,3,4,5,6,7,8,9,10],[11,12,13,14,15,16,17,18,19,20])

[100   1   2   3   4   5   6   7   8   9]
[100   1   2   3   4   5   6   7   8 900]


array([100,  11,   1,  12,   2,  13,   3,  14,   4,  15,   5,  16,   6,
        17,   7,  18,   8,  19,   9,  20])

In [122]:
print(x2)
np.delete(x2,0)

[100   1   2   3   4   5   6   7   8   9]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])