In [1]:
!pip install numpy

In [5]:
import numpy as np

In [7]:
a = np.array([1,2,3,4,5,'a'])

In [8]:
a

array(['1', '2', '3', '4', '5', 'a'], dtype='<U21')

In [9]:
a = np.array([1,2,3,4,5,5.7])

In [10]:
a

array([1. , 2. , 3. , 4. , 5. , 5.7])

In [11]:
a = np.array([1,2,3,4,5,])

In [12]:
a

array([1, 2, 3, 4, 5])

In [14]:
a= np.array(10)
b= np.array([1,2,3])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6],[1,2,3],[4,5,6]]])


In [15]:
print('a dimension:',a.ndim)
print('b dimension:',b.ndim)
print('c dimension:',c.ndim)
print('d dimension:',d.ndim)

a dimension: 0
b dimension: 1
c dimension: 2
d dimension: 3


In [16]:
print(a)
print('shape of a:',a.shape)
print(b)
print('shape of b:',b.shape)
print(c)
print('shape of c:',b.shape)
print(d)
print('shape of d:',d.shape)


10
shape of a: ()
[1 2 3]
shape of b: (3,)
[[1 2 3]
 [4 5 6]]
shape of c: (3,)
[[[1 2 3]
  [4 5 6]
  [1 2 3]
  [4 5 6]]]
shape of d: (1, 4, 3)


In [17]:
print(a.dtype)
print(b.dtype)
print(c.dtype)
print(d.dtype)

int64
int64
int64
int64


In [18]:
print(type(a))
print(type(b))
print(type(c))
print(type(d))


<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [24]:
len(d)


1

In [25]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [27]:
np.eye(8,dtype= int)

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1]])

In [28]:
np.eye(5,dtype= int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [30]:
np.zeros((10,8),dtype ='int')

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [32]:
np.ones((6,6),dtype ='int')

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [35]:
np.full((8,5),7,dtype='int')

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [37]:
x=[25,3,3,4,5,6,7,8,9,50]
np.diag(x)

array([[25,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  3,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  3,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  4,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  5,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  6,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  7,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  8,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  9,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 50]])